#ifndef __RTX_SIGNAL_H
#define __RTX_SIGNAL_H	 

#define UART_RECRIVE_START_SIGNAL 0x01
#define UART_SEND_START_SIGNAL 0X02
#define UART_SEND_FINISH_SIGNAL 0X03
#define TIME2_TIMEOUT_SIGNAL 0X04
#define KEY0_PRESSED_SIGNAL 0X05
#define KEY1_PRESSED_SIGNAL 0X06

#endif
